### ISSUE TITLE
Database persistence and newer web2py?

### ISSUE THREAD

**Issue by AlecTaylor** [prelegalwonder/openshift_web2py#5] opened 2012-08-25 14:03 UTC
Was planning to wait until web2py 2.0 was officially released, but maybe now would be a good time to upgrade this repo to the latest trunk?

Also about database persistence, whenever I push to my OpenShift site/repo the database gets reset.

I'm thinking to configure using rhc a postgres database and connect web2py to that.

Is that the recommended method?'

Thanks for all suggestions,

Alec Taylor

**Comment by prelegalwonder** [comment] 2012-08-26 14:19
I can upgrade the dev branch to the latest trunk. I'll wait for 2.0 to upgrade the master. 

So I need to add some details about db to the README, I've just been neglecting that. Sqlite is configured by default, if you look in the wsgi/application file it's setup to write it to the $OPENSHIFT_DATA_DIR which is the persistent data store on the instance that isn't touched between deploys. 

The only other thing you need to do would be to specify the folder ie. db = DAL('sqlite://storage.sqlite',folder=SQLITE_DIR) in your model.

If you want to use the other database cartridges, a similar approach for the url would be taken minus the need for the DATA_DIR. You can see what all the variables are by ssh'ing into your gear and typing 'env'.

**Comment by AlecTaylor** [comment] 2012-08-30 07:45
Great news! - Version 2 is now out! - Please upgrade the master ASAP :)

Also if you could update the main README with some documentation on setting up with their db layer that would be excellent :)

**Comment by prelegalwonder** [comment] 2012-08-30 13:11
Thanks for the heads up Alec :) I'll get the source updated today and if I have time, the readme before the weekend.

**Comment by prelegalwonder** [comment] 2012-08-30 15:08
Master is now at 2.0.2 and any changes made with IDE in cloud will be saved (but not pulled locally on git pull). Will try to get to DB details soon.

**Comment by AlecTaylor** [comment] 2012-08-30 16:31
Thanks, but unfortunately I ran into a bug during testing.

Looks like admin doesn't work... **admin disabled because unable to access password file**

Note that I created the `parameters_443.py` `parameters_80.py` `parameters_8080.py` files through running `web2py.py -p [port-number] -a [password]` 3 times (different port each time).

On further investigation I noticed that the hash representation was different, e.g.: for password "foo" the resulting hash is `password="acbd18db4cc2f85cedef654fccc4a4d8"` whilst in the old version it generated: `password="pbkdf2(1000,20,sha512)$8f3f0a4877494d87$d0a34c7104213af227043212fba0b5
4ce8cbfd50"`.

Maybe this is the cause of the problem?

EDIT: Changing the hashes manually to the old scheme had no affect

Please help me get this working :)

Thanks

**Comment by prelegalwonder** [comment] 2012-08-30 17:31
Alec, how are you trying to update? 

I just created a brand new gear using the instructions from the README and put in my hash and committed and pushed and it works fine. 

My hash format is - password="pbkdf2(1000,20,sha512)$bc0ae8d0f996139a$da49d0998a585a9352c32064443b5453d7c21536"

Are you perhaps still pointing to the dev branch? Make sure you're pointed to master.

**Comment by SamuelMarks** [comment] 2012-08-30 22:41
I created a new app, following all the commands of your tutorial.

Also tried replacing hash with old format.

It still isn't working though; I can't login to admin.

**Comment by prelegalwonder** [comment] 2012-08-30 23:12
What message are you getting?

**Comment by AlecTaylor** [comment] 2012-08-31 00:14
**admin disabled because unable to access password file**

(I also did a `git add` on the `parameters_*` files just to be sure)

**Comment by prelegalwonder** [comment] 2012-08-31 00:39
Alec, did you make sure you're using master? Since you were getting the old password hash I was thinking maybe it was pointed at dev?  

Also, are you trying to git pull changes from the template here or are you creating a fresh gear to test?

**Comment by AlecTaylor** [comment] 2012-08-31 00:45
Here is precisely what I did when you published the new version 18 hours ago:
1. `rhc app create -a myappname -t python-2.6`
2. `cd myappname`
3. `git remote add upstream -m master git://github.com/prelegalwonder/openshift_web2py.git`
4. `git pull -s recursive -X theirs upstream master`
5. `git push`

**Comment by prelegalwonder** [comment] 2012-08-31 01:38
Just to clarify, after you've added your hash to the password file, you're executing:

git commit -a -m "added hash to parameters blah" 

before doing git push?

**Comment by AlecTaylor** [comment] 2012-08-31 01:44
Yes, I ran `git commit -am "init"` before doing the `git push`.

**Comment by prelegalwonder** [comment] 2012-08-31 02:26
I'm not sure what to tell you. I'm not able to reproduce and without more info there's not a lot I can do. I did a quick screencast showing my exact steps - https://docs.google.com/open?id=0ByP4lcjOqwkhWElDVi1LZWhDS2c

**Comment by AlecTaylor** [comment] 2012-08-31 03:54
Okay, that's weird.

I did exactly what you did, copying over the parameters file from one I generated with [2012-08-30 22:36:07]; your version being: [2012-08-30 08:09:29]... but it still didn't work.

=(

**Comment by prelegalwonder** [comment] 2012-08-31 04:07
would you mind taking a snapshot and uploading it somewhere so I can download it and take a look? 

rhc app snapshot save -a <yourapp> 

It'll dump a compressed tar that will have your entire gear environment that I can load in my account and play with.

**Comment by AlecTaylor** [comment] 2012-08-31 04:57
Okay, added it with pwd: `ComplexPa@s3`.

You can download it here: https://bitbucket.org/AlecTaylor/rhc-troubleshoot/downloads

(that repo also has the uncompressed version)

**Comment by AlecTaylor** [comment] 2012-08-31 10:36
Oops, sorry—just realised it was set to private—it is now public.

**Comment by prelegalwonder** [comment] 2012-08-31 13:33
What OS are you using and can you show me the exact command you're using to make the symlinks from parameters_8080.py -> parameters_443.py  ?

It should be:  ln -s parameters_8080.py parameters_443.py

When I loaded your snapshot and went into the web2py dir I see this:

parameters_443.py -> password="d48d3a0d14792ea6017aa1168264ebf2"?
parameters_80.py -> password="d48d3a0d14792ea6017aa1168264ebf2"?
parameters_8080.py

It should look like this:

parameters_443.py -> parameters_8080.py
parameters_80.py -> parameters_80.py
parameters_8080.py

In the latest master I've made the symlinks for you so you shouldn't have to do anything, but I haven't tried it on windows.

**Comment by prelegalwonder** [comment] 2012-08-31 13:39
Also,  I only did the following to your snapshot:

From wsgi/web2py

unlink parameters_443.py
unlink parameters_80.py

ln -s parameters_8080.py parameters_443.py
ln -s parameters_8080.py parameters_80.py

git commit -a -m "foo"
git push

And I'm getting the password prompt at:
https://bar-liquidmobile.rhcloud.com/admin

**Comment by AlecTaylor** [comment] 2012-08-31 15:54
Took quite a while to get it working, finally found that the windows cygwin `ln` was to blame.

D:\Projects\bar\wsgi\web2py>type parameters_80.py
!<symlink> ■p a r a m e t e r s _ 8 0 8 0 . p y

Whereas what is should be:

D:\Projects\bar\wsgi\web2py>type parameters_80.py
parameters_8080.py

It is now working, thanks a heap :)

[not closing this issue yet; waiting for the db documentation]

**Comment by prelegalwonder** [comment] 2012-09-01 18:57
Will probably have the DB stuff up today.

**Comment by AlecTaylor** [comment] 2012-09-01 18:58
Excellent =D

**Comment by prelegalwonder** [comment] 2012-09-01 20:13
Added it to the readme.md.

**Closed as completed** 2012-09-07 02:43 UTC
